services:
  caddy:
    image: caddy:latest
    container_name: caddy_server
    restart: unless-stopped
    ports:
      - "80:80"    # HTTP (Let's Encrypt 인증용)
      - "443:443"  # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile   # 위에서 생성한 Caddyfile 마운트
      - caddy_data:/data                   # Caddy 데이터 (인증서 등) 저장용 볼륨
      # - caddy_config:/config             # Caddy 설정 저장용 볼륨 (필요시)
    networks:
      - caddy_network
  code-server:
    image: coding404/init-webide:latest
    container_name: code-server
    restart: always
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - /home/ubuntu/project:/home/coder/project
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/.scp:/home/coder/.scp
      - /home/ubuntu/.scpconf:/home/coder/.scpconf
      - /home/ubuntu/.kube:/home/coder/.kube
      - /home/ubuntu/.config:/home/coder/.config
      - /home/ubuntu/.local:/home/coder/.local
    environment:
      # - PASSWORD=admin12345!!
      - PASSWORD=${PASSWORD}
    command: /home/coder/project
    # command: --auth none /home/coder/project
    group_add:
      # - $(shell getent group docker | cut -d: -f3)
      - ${DOCKER_GID}
    networks:
      - caddy_network

volumes:
  caddy_data:
  kube_config_data:
  tf_scp_config_data:
  tf_scp_v2_config_data:
  code_config:
  code_local:

networks:
  caddy_network:
    driver: bridge
